plugins {
    id 'java'
	id 'maven-publish'
}

version = "a1.0"
group = "usr.skyswimmer"

sourceCompatibility = '1.17'
targetCompatibility = '1.17'

def projectId = "gitplugin"
def projectName = "plugin-git"
def authorName = "SkySwimmer"
def pkg = "${group}.${projectId}"

apply plugin: 'eclipse'
apply plugin: 'idea'

repositories {
    mavenCentral()
    flatDir {
        dirs '../../fluid'
	}
}

jar {
	baseName "${projectName}"
	manifest {
		attributes([
			"Specification-Title": "${projectName}",
			"Specification-Vendor": "${authorName}",
			"Specification-Version": project.version,
			"Implementation-Title": project.name,
			"Implementation-Version": project.version,
			"Implementation-Vendor" :"${authorName}",
			"Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
	}
	includeEmptyDirs = false
}

task javaDocs(type: Javadoc) {
	classpath = sourceSets.main.runtimeClasspath
	source = sourceSets.main.allJava
}

task javadocJar(type: Jar, dependsOn: 'javaDocs') {
	from javadoc
	baseName "${projectName}"
	classifier = 'javadoc'
	exclude "**/extra/**"
}

task sourcesJar(type: Jar, dependsOn: classes) {
	baseName "${projectId}"
	classifier = 'sources'
	from sourceSets.main.allSource
	exclude "**/extra/**"
}

artifacts {
	archives javadocJar
	archives sourcesJar
}

dependencies {
	implementation rootProject.name == "polyscript-runner" ? rootProject : project(":polyscript-runner")
	implementation project(":quicktools-utils")
	implementation project(":connective-http")

	implementation group: 'org.asf.cyan', name: 'Fluid', version: '1.0.0.A33'

	implementation group: 'com.google.code.gson', name: 'gson', version: '2.13.2'

	implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.25.3'
	implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.25.3'

	implementation group: 'org.eclipse.jgit', name: 'org.eclipse.jgit', version: '7.5.0.202512021534-r'
	implementation group: 'org.apache.logging.log4j', name: 'log4j-slf4j2-impl', version: '2.25.3'
}

project.configurations.implementation.canBeResolved = true

task moduledata () {
	doLast {
		for (ResolvedArtifact arti : project.configurations.implementation.resolvedConfiguration.getResolvedArtifacts()) {
			if (arti.getClassifier() != null)
				continue;

		    String outFileNm = arti.name + (arti.getClassifier() != null && !arti.getClassifier().isEmpty() ? "-" + arti.getClassifier() : "")
		    if (outFileNm.equals("polyscript-runner") ||(rootProject.name == "polyscript-runner" ? rootProject : project(":polyscript-runner")).configurations.implementation.resolvedConfiguration.getResolvedArtifacts().stream().anyMatch { t -> compareArtifacts(t, arti)})
		    	continue;
			copy {
				from arti.file
				rename arti.file.getName(), outFileNm + "." + arti.getExtension()
				into "build/plugindist/plugins/${projectName}/libs"
			}
		}
		for (def task : project.tasks) {
			if (task instanceof AbstractArchiveTask) {
				if (!task.getArchiveClassifier().get().isEmpty())
					continue;

				copy {
					from task.getArchiveFile().get()
					rename task.getArchiveFile().get().getAsFile().getName(), task.getArchiveBaseName().get() + (task.getArchiveClassifier().get() != null && !task.getArchiveClassifier().get().isEmpty() ? "-" + task.getArchiveClassifier().get() : "") + "." + task.getArchiveExtension().get()
					into "build/plugindist/plugins"
				}
			}
		}
	}
}

boolean compareArtifacts(ResolvedArtifact arti, ResolvedArtifact t) {
	if (!arti.name.equals(t.name))
		return false;
	if (arti.getClassifier() != null && t.getClassifier() == null || arti.getClassifier() == null && t.getClassifier() != null)
		return false;
	if (!arti.getClassifier().equals(t.getClassifier()))
		return false;
	if (arti.getModuleVersion() != null && t.getModuleVersion() == null || arti.getModuleVersion() == null && t.getModuleVersion() != null)
		return false;
	if (arti.getModuleVersion() != null) {
		if (arti.getModuleVersion().getId() != null && t.getModuleVersion().getId() == null || arti.getModuleVersion().getId() == null && t.getModuleVersion().getId() != null)
			return false;
		if (arti.getModuleVersion().getId() != null) {
			var v1 = arti.getModuleVersion().getId()
			var v2 = t.getModuleVersion().getId()
			if (v1.getGroup() != null && v2.getGroup() == null || v1.getGroup() == null && v2.getGroup() != null)
				return false;
			if (!v1.getGroup().equals(v2.getGroup()))
				return false;
			if (v1.getName() != null && v2.getName() == null || v1.getName() == null && v2.getName() != null)
				return false;
			if (!v1.getName().equals(v2.getName()))
				return false;
			if (v1.getName() != null && v2.getName() == null || v1.getName() == null && v2.getName() != null)
				return false;
			if (!v1.getVersion().equals(v2.getVersion()))
				return false;
		}
	}
	return true;
}

moduledata.dependsOn project.tasks.build
build.finalizedBy moduledata
